### ISSUE TITLE
Unexpected error fetching FYTA Coordinator data: cannot access local variable 'msg' where it is not associated with a value

### ISSUE THREAD

**Issue by resterampeberlin** [dontinelli/fyta-custom_component#18]
### System Health details

See #17

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/dontinelli/fyta-custom_component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

This exception occurs randomly.

### Reproduction steps

Occurs randomly

### Debug logs

```text
2024-03-26 01:23:56.167 ERROR (MainThread) [custom_components.fyta.coordinator] Unexpected error fetching FYTA Coordinator data: cannot access local variable 'msg' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fyta/coordinator.py", line 46, in _async_update_data
    data = await self.fyta.update_all_plants()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 70, in update_all_plants
    plant_list = await self.update_plant_list()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 61, in update_plant_list
    self.plant_list = await self.client.get_plants()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_client.py", line 122, in get_plants
    msg,
    ^^^
UnboundLocalError: cannot access local variable 'msg' where it is not associated with a value
```

**Comment by resterampeberlin** [comment]
This exception occurs independently from #17, see the log below:
2024-03-25 11:42:28.976 ERROR (MainThread) [custom_components.fyta.coordinator] Unexpected error fetching FYTA Coordinator data: 'plant'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fyta/coordinator.py", line 46, in _async_update_data
    data = await self.fyta.update_all_plants()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 73, in update_all_plants
    current_plant = await self.update_plant_data(plant)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 85, in update_plant_data
    plant_data: dict = p["plant"]
                       ~^^^^^^^^^
KeyError: 'plant'
2024-03-25 19:51:30.301 ERROR (MainThread) [custom_components.fyta.coordinator] Unexpected error fetching FYTA Coordinator data: 'plant'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fyta/coordinator.py", line 46, in _async_update_data
    data = await self.fyta.update_all_plants()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 73, in update_all_plants
    current_plant = await self.update_plant_data(plant)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 85, in update_plant_data
    plant_data: dict = p["plant"]
                       ~^^^^^^^^^
KeyError: 'plant'
2024-03-26 01:23:56.167 ERROR (MainThread) [custom_components.fyta.coordinator] Unexpected error fetching FYTA Coordinator data: cannot access local variable 'msg' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fyta/coordinator.py", line 46, in _async_update_data
    data = await self.fyta.update_all_plants()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 70, in update_all_plants
    plant_list = await self.update_plant_list()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_connector.py", line 61, in update_plant_list
    self.plant_list = await self.client.get_plants()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fyta_cli/fyta_client.py", line 122, in get_plants
    msg,
    ^^^
UnboundLocalError: cannot access local variable 'msg' where it is not associated with a value
